title: David M. Cerna's Homepage
page-top-title: Dr. Techn. D.M. Cerna 
top-section-bg-text: Computational Logician
home-subtitle: David M. Cerna, PhD
copyright-text: '&copy; David Cerna 2025. All Rights Reserved.'
